[package]
name = "audio-play-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[dependencies]
android_logger = "0.13.3"
log = "0.4.20"
oboe = "0.5.0"
